// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teacher-profile/VariantA.tsx": () => import("../components/mockups/teacher-profile/VariantA.tsx"),
  "./components/mockups/teacher-profile/VariantB.tsx": () => import("../components/mockups/teacher-profile/VariantB.tsx"),
  "./components/mockups/teacher-profile/VariantC.tsx": () => import("../components/mockups/teacher-profile/VariantC.tsx"),
  "./components/mockups/teacher-profile/VariantD.tsx": () => import("../components/mockups/teacher-profile/VariantD.tsx")
};
